spring.application.name=backend

# Configuración de base de datos H2 (En memoria, ideal para empezar y testear)
spring.datasource.url=jdbc:h2:mem:musicdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA y Hibernate (Crear tablas automáticamente al arrancar)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Habilitar consola web para poder "ver" la base de datos visualmente
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
